nome : gerar animação

em :
  # executado automaticamente a cada 6 horas
-cron     : " 0 */8 * * * " 
  
  # permite executar manualmente o trabalho a qualquer momento
  workflow_dispatch :
  
  # executado em cada push no branch master
  empurre :
    ramos :
    - mestre
    
  

empregos :
  gerar :
    run-on : ubuntu-latest
    minutos de tempo limite : 10
    
    passos :
      # gera um jogo snake a partir de um gráfico de contribuições de um usuário do github (<github_user_name>), gera uma animação svg em <svg_out_path>
      - name : gere github-contribution-grid-snake.svg
        usa : Platane/snk/svg-only@v2
        com :
          github_user_name : RogerioMatos75
          saídas : 
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      # envia o conteúdo de <build_dir> para um branch
      # o conteúdo estará disponível em https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , ou como página do github
      - name : envie github-contribution-grid-snake.svg para a ramificação de saída
        usa : crazy-max/ghaction-github-pages@v2.6.0
        com :
          target_branch : saída
          build_dir : dist
        ambiente :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
