name: Generate Snake

# Controls when the action will run. This action runs on a customizable schedule.

on:
  schedule:
    # Define o intervalo de tempo para a execução da ação (a cada 6 horas, por padrão)
    - cron: "${{ github.action.inputs.schedule || '0 */6 * * *' }}"

  # Permite a execução manual da ação a partir da guia "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Gera a cobra com base nas opções fornecidas
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          # Nome de usuário do GitHub para a cobra
          github_user_name: ${{ github.actor }}
          # Caminho de saída para o arquivo GIF da cobra
          gif_out_path: ${{ github.workspace }}/dist/github-contribution-grid-snake.gif
          # Caminho de saída para o arquivo SVG da cobra
          svg_out_path: ${{ github.workspace }}/dist/github-contribution-grid-snake.svg
          # Personalização da aparência da cobra (cores, tamanho, estilo etc.)
          snake_color: ${{ github.action.inputs.snake_color || 'pink' }}
          background_color: ${{ github.action.inputs.background_color || '#000000' }}
          grid_color: ${{ github.action.inputs.grid_color || '#FFFFFF' }}
          # Intervalo de tempo para a execução da ação (cron)
          schedule: ${{ github.action.inputs.schedule || '0 */6 * * *' }}

      # Exibe o status do build para fins de depuração
      - name: Show build status
        run: git status

      # Faz o push das alterações para o repositório
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica os arquivos gerados no GitHub Pages
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
